### ISSUE TITLE
v0.13 doesn't build with wasm_bindgen

### ISSUE THREAD

**Issue by cauthmann** [rustsim/nphysics#241]
Hello,

I'm trying to use nphysics3d in a wasm-bindgen/wasm-pack project. Moving timer functionality into the instant crate was a good move, but the crate isn't wired up correctly in nphysics.

For example, build/nphysics3d/Cargo.toml says:
```toml
[features]
default = [ "dim3", "stdweb" ]
use-wasm-bindgen = [ "dim3", "wasm-bindgen", "web-sys" ]
dim3    = [ ]

[dependencies]
instant    = { version = "0.1", features = [ "stdweb", "now" ]}
```
instant will always use stdweb. I used a local copy with a slightly changed Cargo.toml:
```toml
[features]
default = [ "dim3", "stdweb", "instant/stdweb" ]
use-wasm-bindgen = [ "dim3", "wasm-bindgen", "web-sys", "instant/wasm-bindgen" ]
dim3    = [ ]

[dependencies]
instant    = { version = "0.1", features = [ "now" ]}
```
I can confirm that these changes allow my project to build with nphysics3d, both native and with wasm-bindgen. I couldn't test whether stdweb still works (hence this is a bug report and not a patch. sorry.)
